### ISSUE TITLE
null_resource local exec bug with Azure Function App deployment

### ISSUE THREAD

**Issue by Annesars90** [hashicorp/terraform-provider-null#100]
### Terraform CLI and Provider Versions

Tested with following terraform versions.
0.12.0
0.15.0
1.1.4

Provider
azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.54.0"
}

### Terraform Configuration

```terraform
data "archive_file" "zip_functions" {
  type        = "zip"
  source_dir  = "C:/Users/../../subscription"
  output_path = "C:/Users/../../subscription.zip"
}

variable "resource_group" {
  type = string
}

variable "name" {
  type = string
}

resource "null_resource" "deploy_functions" {
  
  provisioner "local-exec" {
    command = <<-EOT
    az functionapp deployment source config-zip --src ${data.archive_file.zip_functions.output_path} --resource-group ${var.resource_group} --name ${var.name} --timeout 300
    EOT
  }
}
```

### Expected Behavior

Before deploying the resource, I made sure I'm logged in and set the subscription with az login and az account set
When deploying this resource with the zip file, several things should happen:
1. The code of the function app should be updated (in this case a new powershell function name)
2. The modules of the function app should be updated (in this case a new powershell function)
3. The function app should use the new modules when activated

This works completely fine when just using the az cli command without the terraform null_resource.

### Actual Behavior

When deploying the null_resource the code of the function app is updated (1) and the modules are updated (2). However when running the function app, it doesn't recognize the new module names (3). It seems the function app doesn't refresh the modules that are imported when using the terraform null_resource. 
A workaround is adding an import-module powershell command at the beginning of the run.ps1 file. This shouldn't be necessary however, because the normal behavior of the Function App is that this is always up to date.

Since this behavior is not seen when using the az-cli with the exact same command, it is probably related to the inner working of the terraform null_resource.

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

Medium

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bflad** [comment]
Hi @Annesars90  👋 Thank you for raising this issue.

If you haven't had this question answered already, it would be best to [raise a topic in HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-core/27), where there is a large community of practitioners better equipped to answer them. The `provisioner` block functionality is wholly implemented in Terraform core (outside of individual providers). If you believe there is a bug in that handling, it would be best to [create an issue in the Terraform core issue tracker](https://github.com/hashicorp/terraform/issues/new/choose).
