### ISSUE TITLE
Terraform plan keep suggesting in-place changes for Null resource.

### ISSUE THREAD

**Issue by prashantkalkar** [hashicorp/terraform-provider-null#153]
### Terraform CLI and Provider Versions

Terraform v1.3.1, darwin_amd64

provider registry.terraform.io/hashicorp/null v3.1.1

### Terraform Configuration

```terraform
locals {
  reboot_script = [
    "sudo reboot &",
  ]
}

resource "null_resource" "node_reboot" {
  triggers = {
    private_ip    = aws_instance.node.private_ip
    user          = local.node_config.instance_user
    password      = local.node_config.instance_user_password
    reboot_script = md5(join(",", local.reboot_script))
  }
  connection {
    host                = local.connection.host
    user                = local.connection.user
    password            = local.connection.password
    private_key         = local.connection.private_key
    bastion_host        = local.connection.bastion_host
    bastion_user        = local.connection.bastion_user
    bastion_private_key = local.connection.bastion_private_key
    timeout             = local.connection.timeout
  }
  provisioner "remote-exec" {
    inline = local.reboot_script
  }
  depends_on = [null_resource.disk1_data, null_resource.disk2_mount]
}
```

### Expected Behavior

The null_resource should not report for update (or even replacement) after terraform apply.

### Actual Behavior

The terraform plan keeps on showing following as part of the plan output even when tf apply is completed. 

```
# module.module1.null_resource.node_reboot will be updated in-place
~ resource "null_resource" "node_reboot" {
      id       = "1931086068078653693"
      # (1 unchanged attribute hidden)
}
```

There seems to be 3 issues I am facing. 

1. The null_resource should not report any changes.
2. Even if there are changes it should report the changes as replacement rather than in-place changes. 
3. The terraform plan should provide information about what is being changed (the plan output does not show any change to be done - as seen above. Not sure what is being changed in-place here). 

Any subsequent apply fails in this case as null_resource does not support in-place changes. 

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

### Additional Information

Do let me know if any other information is required. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prashantkalkar** [comment]
Just to provide more context, I am using the aws provider version 4.32.0. 
I have also configured the **default_tags** at the aws provider level. 

This cause to add tags to all resources. This causing following changes in the plan even after complete terraform apply is successfully done. 

```
# module.module_name_redacted.aws_instance.node will be updated in-place
~ resource "aws_instance" "node" {
      id                                   = "<instanceIPRedacted>"
      tags                                 = {
          "Name"               = "<instanceNameRedacted>"
      }
    ~ volume_tags                          = {
        - "Applications"              = "<Redacted>" -> null
        - "Environment"               = "<Redacted>" -> null
        - "Managed By"                = "Terraform" -> null
        - "Project"                   = "<redacted>" -> null
          # (2 unchanged elements hidden)
      }
      # (30 unchanged attributes hidden)

      # (9 unchanged blocks hidden)
  }

# module.module_name_redacted.null_resource.node_reboot will be updated in-place
~ resource "null_resource" "node_reboot" {
      id       = "<IdRedacted>"
      # (1 unchanged attribute hidden)
  }
```

I am not sure whether this will further help solve the issue. But providing the information in case it's needed.

**Comment by SBGoods** [comment]
Hi @prashantkalkar, thank you for raising this issue and providing the additional context. Can you upgrade the Null Provider to v3.2.0 and see if you can replicate the same issue in that version? Null Provider v3.2.0 is written in the Terraform Provider Framework as opposed to SDKv2 as in previous versions, and therefore the codebase is different in this version. We just want to cover our bases and make sure that this bug is still present in the Framework version of this provider.

Please reach out if you have any further questions!

**Comment by prashantkalkar** [comment]
@SBGoods Thanks for the suggestion. 

I updated the null_resource version to v3.2.0 and generated a new terraform plan. Following is the plan.

`# module.module_name_redacted.aws_instance.node will be updated in-place
~ resource "aws_instance" "node" {
      id                                   = "<instanceIPRedacted>"
      tags                                 = {
          "Name"               = "<instanceNameRedacted>"
      }
    ~ volume_tags                          = {
        - "Applications"              = "<Redacted>" -> null
        - "Environment"               = "<Redacted>" -> null
        - "Managed By"                = "Terraform" -> null
        - "Project"                   = "<redacted>" -> null
          # (2 unchanged elements hidden)
      }
      # (30 unchanged attributes hidden)

      # (9 unchanged blocks hidden)
  }

# module.module_name_redacted.null_resource.node_reboot will be updated in-place
~ resource "null_resource" "node_reboot" {
      id       = "<IdRedacted>"
     ~ triggers = {
        + "password"      = (sensitive)
          # (3 unchanged elements hidden)
      }
  }`

When I applied above changes it worked without any issues (earlier I was getting an error where null_resource was complaining that in-place updates are not supported). 

The another improvement I can see is the subsequent plan did not suggest any changes to the null_resource (which was not the case previously. Earlier the changes were always suggested even when apply was complete. 

I still have a question about the behaviour, should/can the null_resource perform in-place changes for extra trigger attributes as seen in the plan? 
In this particular case, my case it was not an issue since I know I have applied all the changes already. But otherwise shouldn't the null_resource suggest a replacement rather than in-place changes. 

If you believe that the null_resource is behaving as expected then you can close this issue otherwise the issue has to be fixed.

**Comment by rg-irm** [comment]
I'm experiencing a similar issue with null_resource provider version 3.2.0 where null values for trigger values for an existing null_resource are forcing the null_resource to do an in-place update when it shouldn't be making any changes. Below is the plan output when using version 3.2.0. With null_resource provider version 3.1.1, the plan shows "No changes. Your infrastructure matches the configuration."

```
~ resource "null_resource" "update_disks" {
        id       = "<IdRedacted>"
      ~ triggers = {
          + "backup" = null
          + "data"   = null
          + "disk2"  = null
          + "disk3"  = null
          + "disk4"  = null
          + "disk5"  = null
          + "disk6"  = null
          + "disk7"  = null
          + "log"    = null
          + "tempdb" = null
            # (1 unchanged element hidden)
        }
```

**Comment by SBGoods** [comment]
Hi @rg-irm and @prashantkalkar,

Sorry for the late reply. The SDKv2 represents certain empty and null values differently in the Terraform state than the Framework. If you had an existing configuration with the SDKv2 version (<v3.2.0) of the Null provider that had this difference in representation and upgrade to a Framework version (=>v3.2.0) of the provider, then Terraform will plan an in-place replacement of those values to keep the state in parity with what the Framework expects.

Unfortunately, we cannot do anything to prevent this in-place replacement but applying this should have no practical differences in your configurations. If you run into any other issues or have any questions, please feel free to reach out. Thanks!
