### ISSUE TITLE
Error: Provider produced invalid plan

### ISSUE THREAD

**Issue by randhir2021** [hashicorp/terraform-provider-null#163]
### Terraform CLI and Provider Versions

Terraform v0.13.6
 -/null: version = "~> 3.2.1"

### Terraform Configuration

```terraform
data "external" "validate_subnets_script" {
  program = ["python", "${path.module}/scripts/validate_subnets.py"]
  query = {
    subnet_id = var.subnet_id
    region    = var.region
    role_arn  = var.role_arn
  }
}

  resource "null_resource" "validate_subnets" {
    triggers = data.external.validate_subnets_script.result["subnet_id"] == var.subnet_id ? {} : file("ERROR: Subnet should be private")
    lifecycle {
      ignore_changes = [
        triggers
      ]
    }
  }
```

### Expected Behavior

This should have generated a normal plan and shown resources to change/update/delete/create.

### Actual Behavior

Error: Provider produced invalid plan

Provider "registry.terraform.io/hashicorp/null" planned an invalid value for
module.ec2-instance-pp-vtsy32abopqhw.null_resource.validate_subnets.triggers:
planned value cty.NullVal(cty.Map(cty.String)) does not match config value
cty.MapValEmpty(cty.String).

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Steps to Reproduce

This issue doesn't occur when provider version is passed. works correctly with below configuration. However when the version is not passed it takes latest and shows error.
provider "null" {
  version = "< 3.2.0"
}

### How much impact is this issue causing?

High

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SBGoods** [comment]
Hi @randhir2021,
Thank you for taking the time to open this issue and sorry that you are running into trouble here.
Can you provide a bit more detail about your configuration? I'm having a bit of trouble reproducing this issue on my end.
This is what I ran on my end to try to reproduce this:

Terraform Configuration
```Terraform
terraform {
  required_providers {
    null = {
      version = ">3.2.0"
      source = "hashicorp/null"
    }
  }
}

variable "subnet_id" {
  default = "1"
}
data "external" "validate_subnets_script" {
  program = ["python3", "${path.module}/test.py"]
}

resource "null_resource" "validate_subnets" {
  triggers = data.external.validate_subnets_script.result["subnet_id"] == var.subnet_id  ? {} : file("ERROR: Subnet should be private")
  lifecycle {
    ignore_changes = [
      triggers
    ]
  }
}
```

Test.py
```Python
import json

var = {"subnet_id": "1"}

json_object = json.dumps(var, indent = 4)
print(json_object)
```
Output
```
data.external.validate_subnets_script: Reading...
data.external.validate_subnets_script: Read complete after 0s [id=-]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.validate_subnets will be created
  + resource "null_resource" "validate_subnets" {
      + id       = (known after apply)
      + triggers = {}
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

I've also tried running this configuration with Null Provider 3.1.1 and then upgrading to version 3.2.1 with the existing state and I'm still having trouble reproducing this issue. Can you share the `validate_subnets` object in your `terraform.tfstate` file?

**Comment by SBGoods** [comment]
Hi @randhir2021, 
Since we haven't heard back from you in a while, I'm going to close out this issue. Please feel free to open up another issue if you are still running into trouble with this.
