### ISSUE TITLE
null_data_source with count not getting referenced correctly

### ISSUE THREAD

**Issue by gaui** [hashicorp/terraform-provider-null#18]
I'm computing a ListMap with `null_data_source` with count and inputs, to create a ListMap with specific keys and values from a list of hostnames and IP addresses, based on a dynamic created  VMs.

My `null_data_source` looks like this:

Then I pass the outputs as a `nodes` variable into a module where I reference them in a resource. When I output the `nodes` inside the module, I get the correct output, but the resource doesn't.

```
data "null_data_source" rke_nodes {
  count = "${var.node_count}"

  inputs = {
    address = "${element(module.cluster_nodes.node_ips, count.index)}"
    user    = "${var.ssh_username}"
    roles   = "controlplane,etcd,worker"
    ssh_key = "${var.ssh_private_key}"
  }
}

module rke {
  source = "./rke"

  ssh_username    = "${var.ssh_username}"
  ssh_private_key = "${var.ssh_private_key}"

  cluster_dns_fqdn = "${var.cluster_dns_fqdn}"

  nodes      = ["${data.null_data_source.rke_nodes.*.outputs}"]
}
```

Then inside the `rke` module I use the `nodes` variable like the following:

```
resource "rke_cluster" rke_cluster {
   nodes = ["${var.nodes}"]

   ingress = {
     provider = "none"
   }
 }
```

The error I get:

```
Error: module.vsphere.module.rancher.module.rancher_cluster.module.rke.rke_cluster.rke_cluster: "nodes.0.address": required field is not set
```

But when I output the `nodes.0.address` and read it with `terraform output` command I get the IP address expected. See below:

```
output ip {
    value = "${lookup(var.nodes[0], "address")}"
}

$ terraform output -module=rke ip
192.168.176.55
```

How can this be solved?

**Comment by yzargari** [comment]
Hi @gaui,
Were you able to figure this out? I'm having the exact same problem (with a different resource, but still same symptoms)...

Thanks,
Yosi

**Comment by bflad** [comment]
Hi @gaui 👋 Thank you for raising this. Hopefully in the time since this has been raised, this has been answered via a configuration update, provider update, or Terraform update. If not, I would suggest [creating a topic in HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-core/27) where a larger community of practitioners is active.
