### ISSUE TITLE
v1.0.0 MacOS (Ventura 13.4.1) Provider Segmentation Fault

### ISSUE THREAD

**Issue by thatguyfig** [hashicorp/terraform-provider-null#243]
### Terraform CLI and Provider Versions

Terraform: 0.11.14
Provider: 1.0.0

### Terraform Configuration

```terraform
resource "null_resource" "shell" {
  provisioner "local-exec" {
    command = "ls -l"
  }
}

provider "null" {
  version = "~> 1.0"
}
```

### Expected Behavior

Plan to be produced successfully.

### Actual Behavior

Process fails and outputs:

Error: Error asking for user input: 1 error occurred:
        * provider.null: plugin exited before we could connect

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. The provider fails to initialise and produces the error log.

### How much impact is this issue causing?

High

### Logs

2023/07/18 09:53:14 [INFO] Terraform version: 0.11.14  
2023/07/18 09:53:14 [INFO] Go runtime version: go1.12.4
2023/07/18 09:53:14 [INFO] CLI args: []string{"/opt/homebrew/Cellar/tfenv/3.0.0/versions/0.11.14/terraform", "plan"}
2023/07/18 09:53:14 [DEBUG] Attempting to open CLI config file: /Users/gbthornto/.terraformrc
2023/07/18 09:53:14 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2023/07/18 09:53:14 [INFO] CLI command args: []string{"plan"}
2023/07/18 09:53:14 [INFO] command: empty terraform config, returning nil
2023/07/18 09:53:14 [DEBUG] command: no data state file found for backend config
2023/07/18 09:53:14 [DEBUG] New state was assigned lineage "962a5b98-a3ae-136b-3755-0515e3cc3165"
2023/07/18 09:53:14 [INFO] command: backend initialized: <nil>
2023/07/18 09:53:14 [DEBUG] checking for provider in "."
2023/07/18 09:53:14 [DEBUG] checking for provider in "/opt/homebrew/Cellar/tfenv/3.0.0/versions/0.11.14"
2023/07/18 09:53:14 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2023/07/18 09:53:14 [DEBUG] found provider "terraform-provider-null_v1.0.0_x4"
2023/07/18 09:53:14 [DEBUG] checking for provider in "/Users/gbthornto/.terraform.d/plugins"
2023/07/18 09:53:14 [DEBUG] found valid plugin: "null", "1.0.0", "/Users/gbthornto/GitRepos/deploy/terraform/providers/aws/testing/.terraform/plugins/darwin_amd64/terraform-provider-null_v1.0.0_x4"
2023/07/18 09:53:14 [DEBUG] checking for provisioner in "."
2023/07/18 09:53:14 [DEBUG] checking for provisioner in "/opt/homebrew/Cellar/tfenv/3.0.0/versions/0.11.14"
2023/07/18 09:53:14 [DEBUG] checking for provisioner in ".terraform/plugins/darwin_amd64"
2023/07/18 09:53:14 [DEBUG] checking for provisioner in "/Users/gbthornto/.terraform.d/plugins"
2023/07/18 09:53:14 [INFO] command: backend <nil> is not enhanced, wrapping in local
2023/07/18 09:53:14 [INFO] backend/local: starting Plan operation
2023/07/18 09:53:14 [DEBUG] New state was assigned lineage "a934179c-b169-eedd-b70e-f840d871e1a4"
2023/07/18 09:53:14 [INFO] terraform: building graph: GraphTypeInput
2023/07/18 09:53:14 [TRACE] ConfigTransformer: Starting for path: []
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.ConfigTransformer:

null_resource.shell - *terraform.NodeAbstractResource
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.LocalTransformer:

null_resource.shell - *terraform.NodeAbstractResource
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.OutputTransformer:

null_resource.shell - *terraform.NodeAbstractResource
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.OrphanResourceTransformer:

null_resource.shell - *terraform.NodeAbstractResource
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.OrphanOutputTransformer:

null_resource.shell - *terraform.NodeAbstractResource
2023/07/18 09:53:14 [TRACE] AttachResourceConfigTransformer: Beginning...
2023/07/18 09:53:14 [TRACE] AttachResourceConfigTransformer: Attach resource config request: null_resource.shell
2023/07/18 09:53:14 [TRACE] Attaching resource config: &config.Resource{Mode:0, Name:"shell", Type:"null_resource", RawCount:(*config.RawConfig)(0xc0003fa0e0), RawConfig:(*config.RawConfig)(0xc0003fa070), Provisioners:[]*config.Provisioner{(*config.Provisioner)(0xc0003d80c0)}, Provider:"", DependsOn:[]string(nil), Lifecycle:config.ResourceLifecycle{CreateBeforeDestroy:false, PreventDestroy:false, IgnoreChanges:[]string(nil)}}
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.AttachResourceConfigTransformer:

null_resource.shell - *terraform.NodeAbstractResource
2023/07/18 09:53:14 [DEBUG] Resource state not found for "null_resource.shell": null_resource.shell
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.AttachStateTransformer:

null_resource.shell - *terraform.NodeAbstractResource
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.RootVariableTransformer:

null_resource.shell - *terraform.NodeAbstractResource
2023/07/18 09:53:14 [TRACE] ProviderConfigTransformer: Starting for path: []
2023/07/18 09:53:14 [TRACE] Attach provider request: []string{} null
2023/07/18 09:53:14 [TRACE] Attaching provider config: *config.ProviderConfig{Name:"null", Alias:"", Version:"~> 1.0", RawConfig:(*config.RawConfig)(0xc0003fa000)}
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.ProviderConfigTransformer:

null_resource.shell - *terraform.NodeAbstractResource
provider.null - *terraform.NodeApplyableProvider
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.MissingProviderTransformer:

null_resource.shell - *terraform.NodeAbstractResource
provider.null - *terraform.NodeApplyableProvider
2023/07/18 09:53:14 [DEBUG] resource null_resource.shell using provider provider.null
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.ProviderTransformer:

null_resource.shell - *terraform.NodeAbstractResource
  provider.null - *terraform.NodeApplyableProvider
provider.null - *terraform.NodeApplyableProvider
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.PruneProviderTransformer:

null_resource.shell - *terraform.NodeAbstractResource
  provider.null - *terraform.NodeApplyableProvider
provider.null - *terraform.NodeApplyableProvider
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.ParentProviderTransformer:

null_resource.shell - *terraform.NodeAbstractResource
  provider.null - *terraform.NodeApplyableProvider
provider.null - *terraform.NodeApplyableProvider
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.graphTransformerMulti:

null_resource.shell - *terraform.NodeAbstractResource
  provider.null - *terraform.NodeApplyableProvider
provider.null - *terraform.NodeApplyableProvider
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.ModuleVariableTransformer:

null_resource.shell - *terraform.NodeAbstractResource
  provider.null - *terraform.NodeApplyableProvider
provider.null - *terraform.NodeApplyableProvider
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.RemovedModuleTransformer:

null_resource.shell - *terraform.NodeAbstractResource
  provider.null - *terraform.NodeApplyableProvider
provider.null - *terraform.NodeApplyableProvider
2023/07/18 09:53:14 [DEBUG] ReferenceTransformer: "null_resource.shell" references: []
2023/07/18 09:53:14 [DEBUG] ReferenceTransformer: "provider.null" references: []
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.ReferenceTransformer:

null_resource.shell - *terraform.NodeAbstractResource
  provider.null - *terraform.NodeApplyableProvider
provider.null - *terraform.NodeApplyableProvider
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.CountBoundaryTransformer:

meta.count-boundary (count boundary fixup) - *terraform.NodeCountBoundary
  null_resource.shell - *terraform.NodeAbstractResource
  provider.null - *terraform.NodeApplyableProvider
null_resource.shell - *terraform.NodeAbstractResource
  provider.null - *terraform.NodeApplyableProvider
provider.null - *terraform.NodeApplyableProvider
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.TargetsTransformer:

meta.count-boundary (count boundary fixup) - *terraform.NodeCountBoundary
  null_resource.shell - *terraform.NodeAbstractResource
  provider.null - *terraform.NodeApplyableProvider
null_resource.shell - *terraform.NodeAbstractResource
  provider.null - *terraform.NodeApplyableProvider
provider.null - *terraform.NodeApplyableProvider
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.CloseProviderTransformer:

meta.count-boundary (count boundary fixup) - *terraform.NodeCountBoundary
  null_resource.shell - *terraform.NodeAbstractResource
  provider.null - *terraform.NodeApplyableProvider
null_resource.shell - *terraform.NodeAbstractResource
  provider.null - *terraform.NodeApplyableProvider
provider.null - *terraform.NodeApplyableProvider
provider.null (close) - *terraform.graphNodeCloseProvider
  null_resource.shell - *terraform.NodeAbstractResource
  provider.null - *terraform.NodeApplyableProvider
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.CloseProvisionerTransformer:

meta.count-boundary (count boundary fixup) - *terraform.NodeCountBoundary
  null_resource.shell - *terraform.NodeAbstractResource
  provider.null - *terraform.NodeApplyableProvider
null_resource.shell - *terraform.NodeAbstractResource
  provider.null - *terraform.NodeApplyableProvider
provider.null - *terraform.NodeApplyableProvider
provider.null (close) - *terraform.graphNodeCloseProvider
  null_resource.shell - *terraform.NodeAbstractResource
  provider.null - *terraform.NodeApplyableProvider
provisioner.local-exec (close) - *terraform.graphNodeCloseProvisioner
  null_resource.shell - *terraform.NodeAbstractResource
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.RootTransformer:

meta.count-boundary (count boundary fixup) - *terraform.NodeCountBoundary
  null_resource.shell - *terraform.NodeAbstractResource
  provider.null - *terraform.NodeApplyableProvider
null_resource.shell - *terraform.NodeAbstractResource
  provider.null - *terraform.NodeApplyableProvider
provider.null - *terraform.NodeApplyableProvider
provider.null (close) - *terraform.graphNodeCloseProvider
  null_resource.shell - *terraform.NodeAbstractResource
  provider.null - *terraform.NodeApplyableProvider
provisioner.local-exec (close) - *terraform.graphNodeCloseProvisioner
  null_resource.shell - *terraform.NodeAbstractResource
root - terraform.graphNodeRoot
  meta.count-boundary (count boundary fixup) - *terraform.NodeCountBoundary
  provider.null (close) - *terraform.graphNodeCloseProvider
  provisioner.local-exec (close) - *terraform.graphNodeCloseProvisioner
2023/07/18 09:53:14 [TRACE] Graph after step *terraform.TransitiveReductionTransformer:

meta.count-boundary (count boundary fixup) - *terraform.NodeCountBoundary
  null_resource.shell - *terraform.NodeAbstractResource
null_resource.shell - *terraform.NodeAbstractResource
  provider.null - *terraform.NodeApplyableProvider
provider.null - *terraform.NodeApplyableProvider
provider.null (close) - *terraform.graphNodeCloseProvider
  null_resource.shell - *terraform.NodeAbstractResource
provisioner.local-exec (close) - *terraform.graphNodeCloseProvisioner
  null_resource.shell - *terraform.NodeAbstractResource
root - terraform.graphNodeRoot
  meta.count-boundary (count boundary fixup) - *terraform.NodeCountBoundary
  provider.null (close) - *terraform.graphNodeCloseProvider
  provisioner.local-exec (close) - *terraform.graphNodeCloseProvisioner
2023/07/18 09:53:14 [DEBUG] Starting graph walk: walkInput
2023/07/18 09:53:14 [TRACE] dag/walk: added new vertex: "root"
2023/07/18 09:53:14 [TRACE] dag/walk: added new vertex: "null_resource.shell"
2023/07/18 09:53:14 [TRACE] dag/walk: added new vertex: "provider.null"
2023/07/18 09:53:14 [TRACE] dag/walk: added new vertex: "meta.count-boundary (count boundary fixup)"
2023/07/18 09:53:14 [TRACE] dag/walk: added new vertex: "provider.null (close)"
2023/07/18 09:53:14 [TRACE] dag/walk: added new vertex: "provisioner.local-exec (close)"
2023/07/18 09:53:14 [TRACE] dag/walk: added edge: "null_resource.shell" waiting on "provider.null"
2023/07/18 09:53:14 [TRACE] dag/walk: added edge: "meta.count-boundary (count boundary fixup)" waiting on "null_resource.shell"
2023/07/18 09:53:14 [TRACE] dag/walk: added edge: "provisioner.local-exec (close)" waiting on "null_resource.shell"
2023/07/18 09:53:14 [TRACE] dag/walk: added edge: "root" waiting on "provider.null (close)"
2023/07/18 09:53:14 [TRACE] dag/walk: added edge: "root" waiting on "provisioner.local-exec (close)"
2023/07/18 09:53:14 [TRACE] dag/walk: added edge: "provider.null (close)" waiting on "null_resource.shell"
2023/07/18 09:53:14 [TRACE] dag/walk: added edge: "root" waiting on "meta.count-boundary (count boundary fixup)"
2023/07/18 09:53:14 [TRACE] dag/walk: dependencies changed for "meta.count-boundary (count boundary fixup)", sending new deps
2023/07/18 09:53:14 [TRACE] dag/walk: dependencies changed for "provisioner.local-exec (close)", sending new deps
2023/07/18 09:53:14 [TRACE] dag/walk: dependencies changed for "root", sending new deps
2023/07/18 09:53:14 [TRACE] dag/walk: dependencies changed for "provider.null (close)", sending new deps
2023/07/18 09:53:14 [TRACE] dag/walk: dependencies changed for "null_resource.shell", sending new deps
2023/07/18 09:53:14 [TRACE] dag/walk: walking "provider.null"
2023/07/18 09:53:14 [TRACE] vertex 'root.provider.null': walking
2023/07/18 09:53:14 [TRACE] vertex 'root.provider.null': evaluating
2023/07/18 09:53:14 [TRACE] [walkInput] Entering eval tree: provider.null
2023/07/18 09:53:14 [TRACE] root: eval: *terraform.EvalSequence
2023/07/18 09:53:14 [TRACE] root: eval: *terraform.EvalInitProvider
2023-07-18T09:53:14.568+0100 [DEBUG] plugin: starting plugin: path=/Users/gbthornto/GitRepos/deploy/terraform/providers/aws/testing/.terraform/plugins/darwin_amd64/terraform-provider-null_v1.0.0_x4 args=[/Users/gbthornto/GitRepos/deploy/terraform/providers/aws/testing/.terraform/plugins/darwin_amd64/terraform-provider-null_v1.0.0_x4]
2023-07-18T09:53:14.574+0100 [DEBUG] plugin: waiting for RPC address: path=/Users/gbthornto/GitRepos/deploy/terraform/providers/aws/testing/.terraform/plugins/darwin_amd64/terraform-provider-null_v1.0.0_x4
2023-07-18T09:53:14.590+0100 [DEBUG] plugin: plugin process exited: path=/Users/gbthornto/GitRepos/deploy/terraform/providers/aws/testing/.terraform/plugins/darwin_amd64/terraform-provider-null_v1.0.0_x4
2023/07/18 09:53:14 [ERROR] root: eval: *terraform.EvalInitProvider, err: plugin exited before we could connect
2023/07/18 09:53:14 [ERROR] root: eval: *terraform.EvalSequence, err: plugin exited before we could connect
2023/07/18 09:53:14 [TRACE] [walkInput] Exiting eval tree: provider.null
2023/07/18 09:53:14 [TRACE] dag/walk: upstream errored, not walking "null_resource.shell"
2023/07/18 09:53:14 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2023/07/18 09:53:14 [TRACE] dag/walk: upstream errored, not walking "provider.null (close)"
2023/07/18 09:53:14 [TRACE] dag/walk: upstream errored, not walking "provisioner.local-exec (close)"
2023/07/18 09:53:14 [TRACE] dag/walk: upstream errored, not walking "root"
2023/07/18 09:53:14 [DEBUG] plugin: waiting for all plugin processes to complete...

Error: Error asking for user input: 1 error occurred:
        * provider.null: plugin exited before we could connect

### Additional Information

On some further diagnosis, I began by checking the plugin executables themselves by executing them directly.

All plugins bar the null provider ran fine - running the null provider produces a `segmentation fault` error.

For those struggling with this issue, there is a workaround:

1. Install go and required tools
2. Clone the github repo - https://github.com/hashicorp/terraform-provider-null
3. Check out the v1.0.0 branch
4. Install go packages with `go install` etc.
5. Once dependencies installed - run `make build`
6. Copy the resulting executable to your `.terraform/plugins/darwin_amd64/` folder
7. Generate an updated hash for the new executable using `shasum -a 256 ./terraform/plugins/darwin_amd64/terraform-provider-null_v1.0.0_x4`
8. Update the `.terraform/plugins/darwin_amd64/lock.json` file with the hash from above.
9. `terraform plan` now completes successfully.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bookshelfdave** [comment]
Hello - 

Thanks for reporting this issue, however, we're only able to support usage with Terraform v0.12+. It's possible that this may be resolved with the latest versions of Terraform and the null provider (v3.2.1), although I understand that it may not be possible for you to upgrade. 

Cheers -
Dave
