### ISSUE TITLE
terraform-provider-null_v3.2.1_x5.exe is reporting as TROJAN !!

### ISSUE THREAD

**Issue by inspiringpeople98** [hashicorp/terraform-provider-null#252]
### Terraform CLI and Provider Versions

Terraform v0.12.31

### Terraform Configuration

```terraform
terraform {
  required_version = "= 0.12.31"
  required_providers {
    aws      = "~> 3.0"
    null     = "~> 3.0"
    template = "~> 2.2.0" # provider now archived
    dns      = "~> 3.0"
  }
}
```

### Expected Behavior

terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "dns" (hashicorp/dns) 3.3.2...
- Downloading plugin for provider "null" (hashicorp/null) 3.2.1...
- Downloading plugin for provider "template" (hashicorp/template) 2.2.0...
- Downloading plugin for provider "aws" (hashicorp/aws) 3.76.1...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

### Actual Behavior

![null provider TROJAN](https://github.com/hashicorp/terraform-provider-null/assets/72336771/4ae9313a-0274-4197-b183-f274d249a928)

### Steps to Reproduce

1. terraform init
2. terraform refresh
3. terraform plan
4. terraform apply

Any of the above needs null resources being used, but its working as being deleted by antivirus (TROJAN detected).

### How much impact is this issue causing?

High

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by austinvalle** [comment]
Hi there @inspiringpeople98 👋🏻 ,

For AV, we typically use http://virustotal.com/ to get an idea of what other AV systems think of the binary and if there are false flags being raised (as it's difficult for us to determine why an AV engine, especially the ML-driven ones, would flag this binary).

Running the null provider through that I only see 3/71 vendors raising a flag:
![image](https://github.com/hashicorp/terraform-provider-null/assets/8650838/c4980bea-64b1-47d7-b727-27100a108095)

I don't see any other reports of this for the null provider, so I'm going to close the issue, but if you have additional information or concerns you can report those directly to HashiCorp security: https://www.hashicorp.com/security#vulnerability-reporting
