### ISSUE TITLE
Failing to install provider

### ISSUE THREAD

**Issue by Victor-Agali** [hashicorp/terraform-provider-null#282]
### Terraform CLI and Provider Versions

Initializing the backend...
Upgrading modules...
- ec2 in modules/ec2
- emr in modules/emr
- iam in modules/iam
- kms in modules/kms
Downloading git::ssh://git@git.tech.work.com/module...
Enter passphrase for key '/Users/johnphillip/.ssh/id_rsa': 
- label_module in .terraform/modules/label_module
- lambda in modules/lambda
- s3 in modules/s3

Initializing provider plugins...
- Finding hashicorp/aws versions matching "5.26.0"...
- Finding latest version of hashicorp/archive...
- Finding latest version of hashicorp/null...
- Installing hashicorp/aws v5.26.0...
- Installed hashicorp/aws v5.26.0 (signed by HashiCorp)
- Installing hashicorp/archive v2.4.0...
- Installed hashicorp/archive v2.4.0 (signed by HashiCorp)
- Installing hashicorp/null v3.25.0...

### Terraform Configuration

```terraform
provider aws {
  region = "eu-west-1"
}

terraform {
  backend s3 {}
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "5.26.0"
    }
  }
  required_version = ">=1.0.0"
}
```

### Expected Behavior

Terraform should initialise successfully

### Actual Behavior

╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/null v3.25.0: provider binary not found: could not find
│ executable file starting with terraform-provider-null
╵

### Steps to Reproduce

1. `terraform init`

### How much impact is this issue causing?

High

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by austinvalle** [comment]
Hey there @Victor-Agali, based on the error, looks like somewhere in your configuration you might have an invalid version specified for the null provider as `v3.25.0` does not exist. The latest release of `terraform-provider-null` is [`v3.2.2`](https://github.com/hashicorp/terraform-provider-null/releases/tag/v3.2.2)

You can run the `terraform providers` command to get an idea of what is requiring the invalid `3.25.0` version of null.

```terraform
terraform {
  required_providers {
    null = {
      source = "hashicorp/null"
      # This will cause an error during init, there is no v3.25.0 for the null provider
      version = "3.25.0"
    }
  }
}

resource "null_resource" "hello" {}
```

**Comment by Victor-Agali** [comment]
@austinvalle Hi Austin this has been corrected however I am now getting this error. Could you help please?
```

│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/null v3.2.2: provider binary not found: could not find
│ executable file starting with terraform-provider-null
```

**Comment by austinvalle** [comment]
Are you able to provide the terraform version you're using and a snippet of the terraform configuration that's resulting in this error? Unforuntately we won't be able to help much without that additional information.

Using terraform `v1.6.1` and the following config:
```terraform
terraform {
  required_providers {
    null = {
      source  = "hashicorp/null"
      version = "3.2.2"
    }
  }
}

resource "null_resource" "hello" {}

```

Results in a successful init and apply
```bash
 $ terraform init               

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/null versions matching "3.2.2"...
- Installing hashicorp/null v3.2.2...
- Installed hashicorp/null v3.2.2 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

 $ terraform apply -auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.hello will be created
  + resource "null_resource" "hello" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.hello: Creating...
null_resource.hello: Creation complete after 0s [id=5470282681210138924]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

Another reference that may help: https://developer.hashicorp.com/terraform/language/providers#provider-installation

**Comment by austinvalle** [comment]
I don't see anything incorrect in the terraform block you provided so it seems likely to be an environment issue. The error message also suggests that you might have plugin caching enabled (whereas my example was downloading from the public registry). May be worth checking your cache to ensure you have `3.2.2` of provider null available.

More info on caching if that's relevant to you: https://developer.hashicorp.com/terraform/cli/config/config-file#provider-plugin-cache

If you're still running into trouble after checking that cache, I'd recommend asking further questions in the general [terraform discuss board](https://discuss.hashicorp.com/c/terraform-core/27) or [opening an issue in the main Terraform repository](https://github.com/hashicorp/terraform/issues) if you believe there is a bug in finding that provider version.
