### ISSUE TITLE
Add updatable attribute 

### ISSUE THREAD

**Issue by rucciva** [hashicorp/terraform-provider-null#50]
Since external references from destroy provisioners are now deprecated, those who use `null_resource` to run destroy provisioner as last resort clean up after the actual resource is destroyed will be forced to use `triggers` to store connection information and other related information. Now changes in connection information or any variables used in destroy provisioner will trigger the destroy command, even though the actual resource is not destroyed. It would be helpful if null resource has updatable attribute that does not triggers resource destruction when changed.

### Terraform Version
Terraform v0.13.4

### Affected Resource(s)
Please list the resources as a list, for example:
- null_resource

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "null_resource" "destroyer" {
  triggers = {
    ssh_host = var.ssh["host"]
    ssh_port = var.ssh["port"]
    ssh_user = var.ssh["user"]
    ssh_password = var.ssh["password"]
    ssh_private_key = var.ssh["private_key"]
    
    docker_host_base_path = local.docker_host_base_path
    docker_container_name = local.docker_container_name
  }

  connection {
    type        = "ssh"
    host        = self.triggers.ssh_host
    port        = self.triggers.ssh_port
    user        = self.triggers.ssh_user
    password    = self.triggers.ssh_password
    private_key = self.triggers.ssh_private_key
  }

  provisioner "remote-exec" {
    when = destroy
    on_failure = continue
    inline = [
      "mv ${self.triggers.docker_host_base_path} /tmp/destroyed-${self.triggers.docker_container_name}-${timestamp()}",
    ]
  }
}

resource "docker_container" "some_container_that_mount_host_directory_and_write_to_it" {
   depends_on = [ null_resource.destroyer ]
   ...
}
```

### Debug Output
-

### Panic Output
-

### Expected Behavior
Destruction command should not be triggered by changes in connection information

### Actual Behavior
Destruction command executed.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. update connection information such as password
1. `terraform apply`

### References

**Comment by bflad** [comment]
Terraform 1.4 will contain a new `terraform_data` resource which can accept input data of any type, reflections of that data into an unknown output of the same type, and value updates. Terraform prereleases are available if anyone wants to try out the upcoming functionality.

Reference: https://github.com/hashicorp/terraform/blob/main/website/docs/language/resources/terraform-data.mdx

**Comment by bflad** [comment]
Terraform 1.4.0 has been released today with the new [`terraform_data` resource](https://developer.hashicorp.com/terraform/language/resources/terraform-data). It should support in-place state updates via its `input` attribute. If there are any feature requests or bug reports with the `terraform_data` resource, please [create an issue in the Terraform core issue tracker](https://github.com/hashicorp/terraform/issues/new/choose).
