### ISSUE TITLE
How to use version 3.1.0 ?

### ISSUE THREAD

**Issue by onimsha** [hashicorp/terraform-provider-null#64]
### Terraform Version
Terraform v0.14.7

### Affected Resource(s)
null_resource

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    null = {
      source  = "hashicorp/null"
      version = "3.1.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "3.1.0"
    }
  }
}
```

### Debug Output
```
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/random: no available releases match the given constraints ~> 2.2,
3.1.0


Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/null:
no available releases match the given constraints ~> 2.1, 3.1.0
```

### Expected Behavior
Terraform should be able to download version 3.1.0 of null provider as the current registry release

### Actual Behavior
The maximum version of null provider terraform can install is 2.1.2

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`

**Comment by bflad** [comment]
Hi @onimsha 👋  Were you able to resolve your issue? Using the [`terraform providers` command](https://www.terraform.io/docs/cli/commands/providers.html) might help show where Terraform CLI believes the lower version constraints are coming from in your configuration or modules.

**Comment by bflad** [comment]
Closing due to lack of response.
