### ISSUE TITLE
Minor spelling error in null_resource documentation

### ISSUE THREAD

**Issue by p5** [hashicorp/terraform-provider-null#71]
Hi there,

Just a small error with the documentation for the null_resource.

### Affected Resource(s)
- null_resource Documentation

Spelling error in the following path:
- docs/resources/resource.md
```hcl
  provisioner "remote-exec" {
    # Bootstrap script called with private_ip of each node in the clutser
    inline = [
      "bootstrap-cluster.sh ${join(" ", aws_instance.cluster.*.private_ip)}",
    ]
  }
```

"Cluster" is misspelled as "clutser" in the commented line.  Should be the following:
```hcl
  provisioner "remote-exec" {
    # Bootstrap script called with private_ip of each node in the cluster
    inline = [
      "bootstrap-cluster.sh ${join(" ", aws_instance.cluster.*.private_ip)}",
    ]
  }
```

**Comment by bflad** [comment]
Hi @p5 👋 Thank you for raising this. It appears this was addressed in https://github.com/hashicorp/terraform-provider-null/pull/150 👍
