### ISSUE TITLE
Do not depreciate null_data_source

### ISSUE THREAD

**Issue by innovate-invent** [hashicorp/terraform-provider-null#73]
https://github.com/hashicorp/terraform-provider-null/blob/8cfb35116b6ee1748bb77c6cdeec18b9b71cf47e/internal/provider/data_source.go#L12-L13

The null_data_source has a use that can not be replaced by current terraform functionality. It provides a proxy depends_on for variables.

```hcl
module "mymodule" {}

module "grant_access" {
  arg1 = module.mymodule.output1
}

data "null_data_source" "wait_for_access" {
  depends_on = [module.grant_access]
  inputs = {
    input1 = module.mymodule.output2
  }
}

module "myothermodule" {
  arg1 = data.null_data_source.wait_for_access.outputs.input1
}
```

The alternative to this would be setting `depends_on = [module.grant_access]` for module.myothermodule which adds a global dependency to all resources within myothermodule rather than only the resources that depend on arg1.

**Comment by KyleKotowick** [comment]
This can also be achieved using the ternary operator:
```
module "myothermodule" {
  arg1 = module.mymodule.output2 == null ? module.mymodule.output2 : module.mymodule.output2
}
```

This will force Terraform to wait to until it knows the value of `module.mymodule.output2` before creating anything within `myothermodule` that depends on `arg1`.

**Comment by innovate-invent** [comment]
good idea, I wonder if there is a more concise alternative
maybe `try(!module.grant_access, module.mymodule.output2)`
