### ISSUE TITLE
Create provider design doc

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-provider-null#82]
Maintenance of the standard library providers prioritises stability and correctness relative to the provider's intended feature set. Create a design document describing this feature set, and any other design considerations which influence the architecture of the provider and what can and cannot be added to it.

**Comment by bflad** [comment]
I believe the current plan is now to ensure the new `terraform_data` resource covers all existing `null` provider use cases. It's most likely that this provider will be deprecated in some manner in the future, given that functionality is baked into Terraform itself. I'm going to close this out on the premise that this provider is to be considered feature complete now. 👍
