### ISSUE TITLE
proposal: Add trigger without ForceNew: true / allow null_resource update

### ISSUE THREAD

**Issue by breml** [hashicorp/terraform-provider-null#91]
### Proposal

We use the `null_resource` with a database migration command, that it self is aware of its state. So there are mainly three operations:

- `migrate up`
- `migrate down`
- `migrate drop`

For our case only the first and the last one are relevant. We would like to execute `migrate up` when ever the `terraform apply` is executed and `migrate drop`, if `terraform destroy` is executed. But this does currently not work, because even a `terraform apply` would first execute the destroy command (see also the linked issues). Of course, dropping the entire DB  in this case is not an option, because we would loose all the data stored in it.

The reason for this is, that currently, the `null_resource` only supports triggers, that have the `ForceNew` attribute set to true (see https://github.com/hashicorp/terraform-provider-null/blob/main/internal/provider/resource.go#L25).

I would like to propose an additional trigger (e.g. `triggers_update` or `triggers_soft`), that has the `ForceNew` attribute set to `false` and therefore would update the resource in place, that is, it would only execute the `create` action on update, without the prior `destroy`.

### Affected Resource(s)
Please list the resources as a list, for example:
- null_resource

### Terraform Configuration Files

Example with the proposed `triggers_update`:

```hcl
resource "null_resource" "test" {
  triggers_update = timestamp()

  provisioner "local-exec" {
    when        = create
    command = "echo create"
  }

  provisioner "local-exec" {
    when        = destroy
    command     = "echo destroy"
  }
}
```

### Expected Behavior

On `terraform apply`, only the `create` action is executed. On `terraform destroy`, the `destroy` action is executed.

### Actual Behavior

Currently this is not possible as pointed out above. The `ForceNew` causes the `destroy` action to happen before the `create` action, if there is already a resource existing.

### References

- #52 
- #8

**Comment by agrzegorczyk-leonsoftware** [comment]
+1
I like the idea, and I see some potential use in our infrastructure for that feature.
Our current workaround for that problem is to having 2 null_resource - one for creating / updating and separate one for destroying only. But this have some limitations in some edge cases.
I may only suggest to change parameter name, to be more self-describing, e.g.
trigger_policy = "recreate"|"update"
Alternatively having an additional provisioner with when = update will be nice too (which presence would change default update/recreation policy).

**Comment by bflad** [comment]
Terraform 1.4 will contain a new `terraform_data` resource which can accept input data of any type, reflections of that data into an unknown output of the same type, and value updates. Terraform prereleases are available if anyone wants to try out the upcoming functionality.

Reference: https://github.com/hashicorp/terraform/blob/main/website/docs/language/resources/terraform-data.mdx

**Comment by bflad** [comment]
Terraform 1.4.0 has been released today with the new [`terraform_data` resource](https://developer.hashicorp.com/terraform/language/resources/terraform-data). It should support in-place state updates via its `input` attribute. If there are any feature requests or bug reports with the `terraform_data` resource, please [create an issue in the Terraform core issue tracker](https://github.com/hashicorp/terraform/issues/new/choose).

**Comment by calohmn** [comment]
@bflad Maybe I'm missing something, but I don't see how the `terraform_data` resource offers any improvement here. There is still no "update-time" provisioner, is there?

If I use for example this:
```
resource "terraform_data" "terraform_data1" {
  input = timestamp()
  provisioner "local-exec" {
    command = "echo 'local-exec'"
  }
  provisioner "local-exec" {
    when    = destroy
    command = "echo 'Destroy-time provisioner'"
  }
}
```
the initial `terraform apply` will create the resource and run the `echo 'local-exec'` command, but every subsequent `terraform apply` won't run the command:
```
  # terraform_data.terraform_data1 will be updated in-place
  ~ resource "terraform_data" "terraform_data1" {
        id     = "2f263b80-e83a-e11a-9ce5-c50ecf389690"
      ~ input  = "2023-06-30T03:48:10Z" -> (known after apply)
      ~ output = "2023-06-30T03:48:10Z" -> (known after apply)
    }
[...]
terraform_data.terraform_data1: Modifying... [id=2f263b80-e83a-e11a-9ce5-c50ecf389690]
terraform_data.terraform_data1: Modifications complete after 0s [id=2f263b80-e83a-e11a-9ce5-c50ecf389690]
```

And using `triggers_replace = timestamp()` in the `terraform_data` resource will mean the destroy-time provisioner is run on every `terraform apply`.
```
  # terraform_data.terraform_data1 must be replaced
-/+ resource "terraform_data" "terraform_data1" {
      ~ id               = "2f263b80-e83a-e11a-9ce5-c50ecf389690" -> (known after apply)
      - input            = "2023-06-30T03:49:43Z" -> null
      - output           = "2023-06-30T03:49:43Z" -> null
      + triggers_replace = (known after apply) # forces replacement
    }
[...]
terraform_data.terraform_data1: Destroying... [id=2f263b80-e83a-e11a-9ce5-c50ecf389690]
terraform_data.terraform_data1: Provisioning with 'local-exec'...
terraform_data.terraform_data1 (local-exec): Executing: ["/bin/sh" "-c" "echo 'Destroy-time provisioner'"]
terraform_data.terraform_data1 (local-exec): Destroy-time provisioner
terraform_data.terraform_data1: Destruction complete after 0s
terraform_data.terraform_data1: Creating...
terraform_data.terraform_data1: Provisioning with 'local-exec'...
terraform_data.terraform_data1 (local-exec): Executing: ["/bin/sh" "-c" "echo 'local-exec'"]
terraform_data.terraform_data1 (local-exec): local-exec
terraform_data.terraform_data1: Creation complete after 0s [id=d7de48e4-aa94-5530-5b64-84ae355d3453]
```

So, in order to implement the use case from the ticket text above
> We would like to execute `migrate up` when ever the `terraform apply` is executed and `migrate drop`, if `terraform destroy` is executed

you would still have to define 2 resources (`null_resource` or `terraform_data`), one with the "create-time" provisioner and a trigger to force replacement on each run , and one separate resource with the "destroy-time" provisioner.

I think, it indeed would be helpful to have a
```
  provisioner "local-exec" {
    when = update
[...]
  }
```
provisioner.

**Comment by Gitopolis** [comment]
Could you please clarify how exactly `terraform_data` supports in-place update?
With `triggers_replace` it executes destroy provisioner and then default provisioner, without `triggers_replace` it completely ignores changes in the input

**Comment by bflad** [comment]
> There is still no "update-time" provisioner, is there?

Correct and that is not a feature that will be solved in this provider codebase. There is no intention of enhancing the `null_resource` managed resource further, given that `terraform_data` managed resource is intended to support all its use cases without the need for an external provider plugin. Provisioners themselves and the `terraform_data` managed resource are maintained within the Terraform core codebase, so a feature request will need to be filed in that separate issue tracker: https://github.com/hashicorp/terraform/issues

> Could you please clarify how exactly terraform_data supports in-place update?

The `input` argument of the `terraform_data` resource supports in-place updates without resource replacement, if that is not the behavior you are received, I would suggest filing a bug report. If you have general usage questions about the `terraform_data` resource, please reach out in [HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-core/27). If you have a feature request or bug report for the `terraform_data` resource, or are looking for Terraform to support an "update" provisioner, a feature request can be filed at: https://github.com/hashicorp/terraform/issues
